import type { Metadata } from "next";
import { Montserrat, Bungee, Cinzel } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const cinzel = Cinzel({
   weight: "400",
   variable: "--font-cinzel",
   subsets: ["latin"],
});

const montserrat = Montserrat({
   variable: "--font-montserrat",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${montserrat.variable} ${cinzel.variable} antialiased`}
         >
            <Header />
            {children}
            <Footer />
         </body>
      </html>
   );
}
