import type { Metadata } from "next";
import { Montserrat, Bungee } from "next/font/google";
import "./globals.css";

const bungee = Bungee({
   weight: "400",
   variable: "--font-bungee",
   subsets: ["latin"],
});

const montserrat = Montserrat({
   variable: "--font-montserrat",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${montserrat.variable} ${bungee.variable} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
